with-expecter: true
packages:
  github.com/Taras2108/product-catalog-service/internal/app/product/contracts:
    config:
      all: true
      dir: mocks/contracts
      outpkg: contracts
  github.com/Taras2108/product-catalog-service/internal/pkg/clock:
    config:
      all: true
      dir: mocks/clock
      outpkg: clock
  github.com/Taras2108/product-catalog-service/internal/commitplan:
    config:
      all: true
      dir: mocks/commitplan
      outpkg: commitplan
  github.com/Taras2108/product-catalog-service/internal/transport/grpc/product:
    config:
      all: true
      dir: mocks/transport/grpc/product
      outpkg: product
